services:
    core: 
        container_name: core
        build:
          dockerfile: ./deploy/osago.Dockerfile
        volumes:
          - ./src/osago:/app
        env_file:
          - .env
        ports:
          - "5100:5100"
    server: #network: bridge
        container_name: server
        build:
          dockerfile: ./deploy/server.Dockerfile
        volumes:
          - ./server/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
          - core
        ports:
          - "80:80"

