services:
    core: 
        container_name: osago_core
        build:
          dockerfile: ./deploy/osago.Dockerfile
        volumes:
          - files-dir:/tmp
          - ./src/osago:/app
        networks:
          - app-network
          - postgres-network
        env_file:
            - .env

    server: #network: bridge
        container_name: server
        build:
          dockerfile: ./deploy/server.Dockerfile
        volumes:
          - ./src/server/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
          - app-network
        depends_on:
          - core
        ports:
          - "80:80"

volumes:
  files-dir:
    external: true

networks:
  app-network:
  postgres-network: